name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

defaults:
  run:
    shell: bash

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.0.2"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.2.2"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.4.4"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.6.5"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.8.4"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "8.10.7" }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "9.0.1"  }
          - { cabal: "3.6", os: ubuntu-latest,  ghc: "9.2.2"  }
      fail-fast: false

    steps:
    # ----------------
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
    # ----------------
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    # ----------------
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}--${{ github.Shah }}-CACHE_V3
    # ----------------
    - name: Versions
      run: |
        cabal -V
        ghc -V
    # ----------------
    - name: Make sdist
      run: |
        mkdir sdist
        cabal sdist -o sdist
    - name: Unpack
      run: |
        mkdir unpacked
        tar -C unpacked -xzf sdist/type-level-numbers*tar.gz
        cd unpacked
    # ----------------
    - name: cabal check
      run: |
        cabal -vnormal check
    # ----------------
    - name: Build
      run: |
        cabal configure --haddock-all --enable-tests
        cabal build --write-ghc-environment-files=always
    # ----------------
    - name: Test
      run: |
        cabal test
